# This specifies the version of the Docker Compose file format being used.
version: '3.6'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGOURI=mongodb+srv://mongodb:mongodb@mongodb.fg9uu.mongodb.net/?retryWrites=true&w=majority&appName=mongodb/mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

